/**
 * LYO Audit Findings — 2026-08-05
 *
 * TypeScript encoding of telemetry gap analysis, §5.3 credit synthesis status,
 * and recommendations. Replaces the markdown files in problems/ with typed
 * data structures that can be used programmatically.
 *
 * Source markdown files (preserved for human reading):
 * - problems/2026-08-05-telemetry-gap-root-cause.md
 * - problems/2026-08-05-counterfactual-credit-synthesis-5-3.md
 * - problems/2026-08-05-recommendations.md
 * - problems/2026-08-05-lyo-trace-audit.md
 */

// ============================================================================
// 1. REPO TELEMETRY STATUS
// ============================================================================

export interface RepoTelemetryStatus {
  /** Repository path (relative to workspaces root) */
  repoPath: string;
  /** Path to the learning.sqlite database */
  dbPath: string;
  /** System version that created this database */
  systemVersion: string;
  /** Whether this is the old v3 system or new 0.3.0 system */
  isLegacy: boolean;
  /** Table row counts */
  tableCounts: TableRowCounts;
  /** Whether the full learning pipeline (plan→run→learn) has executed */
  pipelineExecuted: boolean;
  /** Notes about this repo's state */
  notes: string;
}

export interface TableRowCounts {
  runs: number;
  gaps: number;
  protocols: number;
  learningTraces: number;
  outcomes: number;
  preferencePairs: number;
  hookEvents: number;
  hookNormalization: number;
  agentSessions: number;
  sessionPrompts: number;
  jobs: number;
  pathActivations: number;
  commandActivations: number;
  workspaces: number;
  zones: number;
  zoneActivations: number;
  zoneCoactivations: number;
  zoneAssociations: number;
  /** All other tables combined */
  otherTables: number;
  /** Total tables in schema */
  totalTables: number;
}

/** Observed telemetry status for each instrumented repo (2026-08-05) */
export const REPO_TELEMETRY_STATUS: RepoTelemetryStatus[] = [
  {
    repoPath: 'agent-learning-workflow/dogfood/scratch-project',
    dbPath: '.zeroshot/lyo-lessons.db',
    systemVersion: 'v3 (legacy)',
    isLegacy: true,
    tableCounts: {
      runs: 0,
      gaps: 0,
      protocols: 0,
      learningTraces: 0,
      outcomes: 0,
      preferencePairs: 0,
      hookEvents: 0,
      hookNormalization: 0,
      agentSessions: 0,
      sessionPrompts: 0,
      jobs: 0,
      pathActivations: 0,
      commandActivations: 0,
      workspaces: 0,
      zones: 0,
      zoneActivations: 0,
      zoneCoactivations: 0,
      zoneAssociations: 0,
      otherTables: 6, // lesson, lesson_application, lesson_decision, lesson_delta + 2 more
      totalTables: 6,
    },
    pipelineExecuted: true,
    notes: 'Legacy system. Contains 1 lesson (les_9c2a1904eab29b03), 4 applications, 2 decisions, 8 deltas. Generated by run.cjs, not run-loop.sh.',
  },
  {
    repoPath: 'nectr_data_eng-crystalbrooks-env',
    dbPath: '.agent-learning/learning.sqlite',
    systemVersion: '0.3.0',
    isLegacy: false,
    tableCounts: {
      runs: 0,
      gaps: 0,
      protocols: 0,
      learningTraces: 0,
      outcomes: 0,
      preferencePairs: 0,
      hookEvents: 1977,
      hookNormalization: 1977,
      agentSessions: 2,
      sessionPrompts: 0,
      jobs: 2,
      pathActivations: 0,
      commandActivations: 0,
      workspaces: 0,
      zones: 0,
      zoneActivations: 0,
      zoneCoactivations: 0,
      zoneAssociations: 0,
      otherTables: 0,
      totalTables: 28,
    },
    pipelineExecuted: false,
    notes: 'Hooks captured (Claude Code). No pipeline execution. No .claude/settings.json found — likely global SessionStart hook.',
  },
  {
    repoPath: 'nectr-data-lake-rep-744',
    dbPath: '.agent-learning/learning.sqlite',
    systemVersion: '0.3.0',
    isLegacy: false,
    tableCounts: {
      runs: 0,
      gaps: 0,
      protocols: 0,
      learningTraces: 0,
      outcomes: 0,
      preferencePairs: 0,
      hookEvents: 1575,
      hookNormalization: 1575,
      agentSessions: 1,
      sessionPrompts: 0,
      jobs: 1,
      pathActivations: 0,
      commandActivations: 0,
      workspaces: 0,
      zones: 0,
      zoneActivations: 0,
      zoneCoactivations: 0,
      zoneAssociations: 0,
      otherTables: 0,
      totalTables: 28,
    },
    pipelineExecuted: false,
    notes: 'Hooks captured (Claude Code). No pipeline execution. No .claude/settings.json found — likely global SessionStart hook.',
  },
];

/** Repos with zero pipeline executions (the problem) */
export const REPOS_WITHOUT_PIPELINE_EXECUTION = REPO_TELEMETRY_STATUS.filter(
  (r) => !r.pipelineExecuted && !r.isLegacy
).map((r) => r.repoPath);

/** Total hook_events captured but unused for learning */
export const UNUSED_HOOK_EVENTS_TOTAL =
  REPO_TELEMETRY_STATUS
    .filter((r) => !r.isLegacy)
    .reduce((sum, r) => sum + r.tableCounts.hookEvents, 0);

// ============================================================================
// 2. THE SINGLE LESSON (les_9c2a1904eab29b03)
// ============================================================================

export type LessonStatus = 'candidate' | 'active' | 'demoted';

export interface LessonRecord {
  /** Unique lesson identifier */
  lessonId: string;
  /** How the failure was classified */
  failureClass: string;
  /** What triggered this lesson's creation */
  triggerCue: string;
  /** Description of what went wrong */
  explanation: string;
  /** The intervention text delivered to the agent */
  intervention: string;
  /** Current status in the lesson lifecycle */
  status: LessonStatus;
  /** Outcome counters */
  helpfulCount: number;
  harmfulCount: number;
  useCount: number;
  /** Beta posterior: Beta(helpful + 1, harmful + 1) */
  posteriorAlpha: number;
  posteriorBeta: number;
  /** Posterior mean = alpha / (alpha + beta) */
  posteriorMean: number;
}

/** The only lesson in the library as of 2026-08-05 */
export const LESSON_9C2A1904: LessonRecord = {
  lessonId: 'les_9c2a1904eab29b03',
  failureClass: 'output_generation',
  triggerCue: 'missing regression coverage',
  explanation: 'Tests failed: npm test — Errors: - Missing regression coverage',
  intervention: 'Address the validator feedback before retrying. (plus the raw validator output appended)',
  status: 'candidate',
  helpfulCount: 4,
  harmfulCount: 0,
  useCount: 4,
  posteriorAlpha: 5, // helpful + 1
  posteriorBeta: 1,  // harmful + 1
  posteriorMean: 0.833, // 5 / (5 + 1) ≈ 0.833
};

/**
 * Critique: This lesson is a procedural nudge, not a causal explanation.
 * "Fix what the validator told you" is correct but shallow — it doesn't
 * explain WHY the agent omitted tests, only THAT it did.
 */
export const LESSON_CRITIQUE = {
  isProceduralNudge: true,
  lacksCausalExplanation: true,
  wouldPreventFailure: false,
  suggestion: 'Convert to spec constraint: "always write regression test alongside new endpoints"',
} as const;

// ============================================================================
// 3. THE FOUR RUNS THAT PRODUCED THE LESSON
// ============================================================================

export type RunPhase =
  | 'worker_started'
  | 'issue_opened'
  | 'state_snapshot'
  | 'validation_rejected'
  | 'lyo_intervention'
  | 'user_guidance_agent'
  | 'validation_passed'
  | 'lyo_feedback_accepted';

export interface RunTrajectoryStep {
  phase: RunPhase;
  detail?: string;
}

export interface RunRecord {
  /** Unique run identifier */
  runId: string;
  /** Task description */
  task: string;
  /** Model used */
  model: string;
  /** Model provider */
  provider: string;
  /** Agent role */
  role: string;
  /** Thompson sampling score at selection time */
  sampledScore: number;
  /** Decision log ID (if available) */
  decisionId: string | null;
  /** Whether decision log existed at time of run */
  hasDecisionLog: boolean;
  /** Full trajectory through the run */
  trajectory: RunTrajectoryStep[];
}

/** The four runs that all solved "Add a /health endpoint to Express server" */
export const RUNS_THAT_PRODUCED_LESSON: RunRecord[] = [
  {
    runId: 'nimble-nebula-63',
    task: 'Add a /health endpoint to Express server',
    model: 'Claude Haiku',
    provider: 'claude',
    role: 'worker/implementation',
    sampledScore: 0.409,
    decisionId: null,
    hasDecisionLog: false,
    trajectory: [
      { phase: 'worker_started' },
      { phase: 'issue_opened', detail: 'Add a /health endpoint' },
      { phase: 'state_snapshot' },
      { phase: 'validation_rejected', detail: 'Missing regression coverage' },
      { phase: 'lyo_intervention', detail: 'Injects les_9c2a1904eab29b03' },
      { phase: 'user_guidance_agent', detail: '"Address the validator feedback before retrying." + lesson' },
      { phase: 'state_snapshot', detail: 'validation still rejected' },
      { phase: 'validation_passed', detail: 'All tests pass now' },
      { phase: 'lyo_feedback_accepted' },
    ],
  },
  {
    runId: 'quick-bastion-95',
    task: 'Add a /health endpoint to Express server',
    model: 'Claude Haiku',
    provider: 'claude',
    role: 'worker/implementation',
    sampledScore: 0.331,
    decisionId: null,
    hasDecisionLog: false,
    trajectory: [
      { phase: 'worker_started' },
      { phase: 'issue_opened', detail: 'Add a /health endpoint' },
      { phase: 'state_snapshot' },
      { phase: 'validation_rejected', detail: 'Missing regression coverage' },
      { phase: 'lyo_intervention', detail: 'Injects les_9c2a1904eab29b03' },
      { phase: 'user_guidance_agent', detail: '"Address the validator feedback before retrying." + lesson' },
      { phase: 'state_snapshot', detail: 'validation still rejected' },
      { phase: 'validation_passed', detail: 'All tests pass now' },
      { phase: 'lyo_feedback_accepted' },
    ],
  },
  {
    runId: 'misty-surge-90',
    task: 'Add a /health endpoint to Express server',
    model: 'Claude Haiku',
    provider: 'claude',
    role: 'worker/implementation',
    sampledScore: 0.899,
    decisionId: 'dec_7d142626fb9c8fa8',
    hasDecisionLog: true,
    trajectory: [
      { phase: 'worker_started' },
      { phase: 'issue_opened', detail: 'Add a /health endpoint' },
      { phase: 'state_snapshot' },
      { phase: 'validation_rejected', detail: 'Missing regression coverage' },
      { phase: 'lyo_intervention', detail: 'Injects les_9c2a1904eab29b03' },
      { phase: 'user_guidance_agent', detail: '"Address the validator feedback before retrying." + lesson' },
      { phase: 'state_snapshot', detail: 'validation still rejected' },
      { phase: 'validation_passed', detail: 'All tests pass now' },
      { phase: 'lyo_feedback_accepted' },
    ],
  },
  {
    runId: 'eternal-bastion-0',
    task: 'Add a /health endpoint to Express server',
    model: 'Claude Haiku',
    provider: 'claude',
    role: 'worker/implementation',
    sampledScore: 0.557,
    decisionId: 'dec_9b439c9ad54d6858',
    hasDecisionLog: true,
    trajectory: [
      { phase: 'worker_started' },
      { phase: 'issue_opened', detail: 'Add a /health endpoint' },
      { phase: 'state_snapshot' },
      { phase: 'validation_rejected', detail: 'Missing regression coverage' },
      { phase: 'lyo_intervention', detail: 'Injects les_9c2a1904eab29b03' },
      { phase: 'user_guidance_agent', detail: '"Address the validator feedback before retrying." + lesson' },
      { phase: 'state_snapshot', detail: 'validation still rejected' },
      { phase: 'validation_passed', detail: 'All tests pass now' },
      { phase: 'lyo_feedback_accepted' },
    ],
  },
];

/** Key observation: first two runs have no decision log (pre-v0.2) */
export const RUNS_WITHOUT_DECISION_LOG = RUNS_THAT_PRODUCED_LESSON.filter(
  (r) => !r.hasDecisionLog
).map((r) => r.runId);

/** Key observation: last two runs have decision records but identical structure:
 * one candidate, null arm = 0, empty context */
export const DECISION_LOG_GAPS = {
  runsWithDecisions: RUNS_THAT_PRODUCED_LESSON.filter((r) => r.hasDecisionLog).map((r) => r.runId),
  problem: 'Decision log exists but does not carry data required for counterfactual credit synthesis',
  missingFields: [
    'candidate_set',
    'per_candidate_propensities',
    'null_arm_record',
    'run_randomness_record (seeds, temperature, model ids)',
  ],
} as const;

// ============================================================================
// 4. THE DELTA LOG (audit trail)
// ============================================================================

export type DeltaActor = 'reflector' | 'validator-rule';
export type DeltaType = 'CREATE' | 'EDIT' | 'MARK_HELPFUL' | 'MARK_HARMFUL' | 'PROMOTE' | 'DEMOTE';

export interface DeltaRecord {
  deltaId: number;
  actor: DeltaActor;
  type: DeltaType;
  description: string;
}

/** The 8 deltas from the dogfood run */
export const DELTA_LOG: DeltaRecord[] = [
  {
    deltaId: 1,
    actor: 'reflector',
    type: 'CREATE',
    description: 'Lesson born from nimble-nebula-63\'s failure',
  },
  {
    deltaId: 2,
    actor: 'validator-rule',
    type: 'MARK_HELPFUL',
    description: 'nimble-nebula-63 passed after injection',
  },
  {
    deltaId: 3,
    actor: 'reflector',
    type: 'EDIT',
    description: 'quick-bastion-95 merged into same lesson',
  },
  {
    deltaId: 4,
    actor: 'validator-rule',
    type: 'MARK_HELPFUL',
    description: 'quick-bastion-95 passed',
  },
  {
    deltaId: 5,
    actor: 'reflector',
    type: 'EDIT',
    description: 'misty-surge-90 merged',
  },
  {
    deltaId: 6,
    actor: 'validator-rule',
    type: 'MARK_HELPFUL',
    description: 'misty-surge-90 passed',
  },
  {
    deltaId: 7,
    actor: 'reflector',
    type: 'EDIT',
    description: 'eternal-bastion-0 merged',
  },
  {
    deltaId: 8,
    actor: 'validator-rule',
    type: 'MARK_HELPFUL',
    description: 'eternal-bastion-0 passed',
  },
];

/** Grounding invariant: Validator (environment) moves counters, not agent self-assessment */
export const GROUNDING_INVARIANT = {
  proposer: 'Reflector',
  disposer: 'Validator',
  description: 'The Reflector proposes lessons, the Validator disposes via helpful/harmful marking',
  verified: true,
} as const;

// ============================================================================
// 5. §5.3 COUNTERFACTUAL CREDIT SYNTHESIS — STATUS
// ============================================================================

export type CreditLevel = 'L0' | 'L1' | 'L2' | 'L3' | 'L4';

export interface CreditLevelStatus {
  level: CreditLevel;
  name: string;
  description: string;
  status: 'working' | 'designed' | 'not_started';
  notes?: string;
}

/** Credit synthesis capability levels */
export const CREDIT_LEVELS: CreditLevelStatus[] = [
  {
    level: 'L0',
    name: 'Receipts',
    description: 'hook_events, trace.json files — raw evidence capture',
    status: 'working',
  },
  {
    level: 'L1',
    name: 'Per-lesson Beta posterior',
    description: 'helpful/harmful counters → Beta distribution',
    status: 'working',
    notes: 'INCOMPLETE: lesson-library.ts updates markdown files only; outcomes table unused',
  },
  {
    level: 'L2',
    name: 'Embedding-based lesson retrieval',
    description: 'Semantic search over lesson corpus',
    status: 'designed',
  },
  {
    level: 'L3',
    name: 'Content compression',
    description: 'Compress lesson content for efficient storage/retrieval',
    status: 'designed',
  },
  {
    level: 'L4',
    name: 'Hindsight classifier credit',
    description: 'Classifier over receipts to assign credit',
    status: 'designed',
  },
];

/**
 * §5.3 Schema gaps — 6 items from §3.4, all unimplemented.
 *
 * These are the columns/tables needed for proper counterfactual credit
 * synthesis using IPW/DR estimation.
 */
export interface SchemaGap {
  /** §3.4 item number */
  itemNumber: number;
  /** What's missing */
  missing: string;
  /** Why it matters */
  consequence: string;
  /** Reference */
  reference: string;
}

export const SCHEMA_GAPS_53: SchemaGap[] = [
  {
    itemNumber: 1,
    missing: 'sampled_score is not propensity',
    consequence: 'Without P(ℓ top-ranked | candidate set, posteriors), IPW/DR estimation is impossible',
    reference: '§3.4 item 1',
  },
  {
    itemNumber: 2,
    missing: 'Candidate set not recorded',
    consequence: 'Don\'t know which lessons competed at decision time or their (α, β) values',
    reference: '§3.4 item 1',
  },
  {
    itemNumber: 3,
    missing: 'Null-arm records missing',
    consequence: 'Cannot distinguish "lesson worked" from "task was easy, would have passed on retry"',
    reference: '§3.4 item 2',
  },
  {
    itemNumber: 4,
    missing: 'Decision-context absent',
    consequence: 'task_id, failure_class, cycle_index, retry_count needed for backdoor adjustment — without them, lift estimates confounded by difficulty',
    reference: '§3.4 item 3',
  },
  {
    itemNumber: 5,
    missing: 'Bandit posterior snapshot ID',
    consequence: 'As Thompson updates, interpretation of past receipts changes — without versioning, past data becomes uninterpretable',
    reference: '§3.4 item 4',
  },
  {
    itemNumber: 6,
    missing: 'Execution randomness not recorded',
    consequence: 'Seeds, temperature, model IDs, tool-trace hashes needed for WCS rung-3 replay — without them, cannot re-execute "this exact run without the lesson"',
    reference: '§3.4 item 5',
  },
];

/** Proposed lesson_decisions table schema (from recommendations) */
export const PROPOSED_LESSON_DECISIONS_SCHEMA = `-- Proposed table to add to src/schema.ts initLedger()
--
-- This table is MISSING from current schema.ts (27 tables exist, but
-- lesson_decisions is not among them).
--
-- Required for: IPW/DR estimation, counterfactual credit synthesis

CREATE TABLE IF NOT EXISTS lesson_decisions (
  decision_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES runs(run_id),
  decision_time TEXT NOT NULL,

  -- Selection logic
  candidate_set JSON NOT NULL,           -- [{lesson_path, sha256, alpha, beta}, ...]
  selected_lesson_path TEXT,             -- NULL = no-lesson arm (control)
  selected_lesson_sha256 TEXT,
  selected_score REAL,                   -- Thompson draw θ (same as current sampled_score)
  selection_propensity REAL,             -- P(selected | candidate_set, posteriors) ← KEY ADDITION

  -- Decision context (backdoor set)
  task_shape TEXT NOT NULL,
  failure_class TEXT,
  cycle_index INTEGER,
  retry_count INTEGER,

  -- Bandit state (for hindsight reinterpretation)
  bandit_posterior_snapshot_id TEXT,

  -- Execution randomness (WCS rung-3 down payment)
  seed TEXT,
  temperature REAL,
  model_id TEXT,
  tool_trace_hash TEXT,

  created_at TEXT NOT NULL
);`;

// ============================================================================
// 6. CURRENT CREDIT PROPAGATION LOGIC (critique)
// ============================================================================

/**
 * Current credit logic in trace-consumer.ts:468-501:
 *
 * ```
 * for each delivered lesson in run:
 *   if failure_class recurred → harmful
 *   elif failure_class was expected (same spec+writer model observed before) → helpful
 *   else → nothing
 * ```
 */
export const CURRENT_CREDIT_LOGIC = {
  location: 'trace-consumer.ts:468-501',
  logic: 'failure_class_recurred ? harmful : expected ? helpful : nothing',
  problems: [
    'Multiple lessons in same run all get same outcome (over-crediting)',
    '"Expected" check is just prior observation existence — not causal contrast',
    'Does not ask "would this have failed without the lesson?"',
  ],
  perInjectionCoefficientMissing: true,
  /** The formula from §3.2 that should be implemented:
   * w_i = ĥ(ℓ_i | s_i, u') / ρ_i - 1
   */
  targetFormula: 'w_i = h(ℓ_i | s_i, u\') / ρ_i - 1',
} as const;

// ============================================================================
// 7. KNOWN LIMITATIONS / GAPS
// ============================================================================

export interface KnownGap {
  /** Gap identifier */
  id: string;
  /** Title */
  title: string;
  /** Description */
  description: string;
  /** Severity: high/medium/low */
  severity: 'high' | 'medium' | 'low';
  /** Affected component */
  component?: string;
}

export const KNOWN_GAPS: KnownGap[] = [
  {
    id: 'GAP-001',
    title: 'Lesson content loop not closed',
    description: 'System learns that its intervention worked, not what the BEST intervention would be. L1 counters work; L4 hindsight classifier not built.',
    severity: 'high',
    component: 'trace-consumer.ts',
  },
  {
    id: 'GAP-002',
    title: 'Counterfactual credit synthesis not deployed',
    description: '§5.3 design exists on paper (propensity-standardized ratio-lift, IPW/DR, per-injection coefficients) but not implemented. Counters still use "all pending injections get the outcome" — the exact over-crediting the papers warn about.',
    severity: 'high',
    component: 'trace-consumer.ts',
  },
  {
    id: 'GAP-003',
    title: 'Schema gap for propensities',
    description: 'lesson_decision table lacks candidate sets, per-candidate propensities, null-arm records, run randomness record. IPW/DR impossible retroactively.',
    severity: 'high',
    component: 'src/schema.ts',
  },
  {
    id: 'GAP-004',
    title: 'Single task, single model, single failure class',
    description: '4 runs, 1 task shape, 1 model (Claude Haiku), 1 failure class (output_generation). Ashby coverage = 1/1 but meaningless with only one class to observe.',
    severity: 'medium',
    component: 'pipeline',
  },
  {
    id: 'GAP-005',
    title: 'No negative evidence',
    description: '4 helpful, 0 harmful. Either lesson is robust, or system hasn\'t generated conditions where it fails. Wilson gate requires n ≥ 8 before promotion, so system has never seen a counterexample.',
    severity: 'medium',
    component: 'lesson-library',
  },
  {
    id: 'GAP-006',
    title: 'No control arm',
    description: 'Without cycles where lesson was NOT injected, cannot separate "lesson worked" from "task is easy, agent would have passed on retry anyway." wouldacouldashoulda-digest.md §6(b.3) warns about this.',
    severity: 'medium',
    component: 'pipeline',
  },
  {
    id: 'GAP-007',
    title: 'Two work repos uninstrumented in practice',
    description: 'nectr_data_eng-crystalbrooks-env and nectr-data-lake-rep-744 have LYO schema but no data. Artifacts directory exists in crystalbrooks-env but no lyo-update.json, trace.json, verifier-report.json.',
    severity: 'high',
    component: 'pipeline',
  },
  {
    id: 'GAP-008',
    title: 'Pipeline and DB not connected',
    description: 'runPipeline() does not call recordRun(). Claude Code hooks don\'t trigger pipeline. Someone must explicitly run lyo pipeline run + lyo run-start + lyo pipeline learn. This didn\'t happen in work repos.',
    severity: 'high',
    component: 'src/runner/run-pipeline.ts:89',
  },
];

// ============================================================================
// 8. ROOT CAUSE SUMMARY
// ============================================================================

export const TELEMETRY_GAP_ROOT_CAUSE = {
  summary: 'Pipeline and DB recording are not connected',
  detail: `Two separate pipelines exist:

1. Hook capture pipeline — captures Claude/Codex events in real-time into observation tables.
   Purpose: record "what happened."

2. Learning pipeline — requires plan.json + spec.json. Code/test writers execute → verifier runs →
   trace.json + verifier-report.json generated → lyo pipeline learn extracts lessons.
   Purpose: record "what was learned."

No bridge between them. hook_events records "Claude Code session ran in this repo" but if that
session never executed 'lyo pipeline run', learning data is zero.`,
  evidence: [
    'src/runner/run-pipeline.ts:89 — runPipeline() does not call recordRun()',
    'src/cli/commands/pipeline.ts:24-40 — pipelineRunCommand returns runPipeline() result only',
    'src/reducers/core.ts:30 — recordRun() only callable via lyo run-start command',
    'src/lyo/trace-consumer.ts:279 — consumeTraces() writes lesson files and lyo-update only',
    'Claude Code hook: handleClaudeHook() → claudeHookObservation() → persistHookObservation()',
    'Hook records: hook_events, hook_normalizations, agent_sessions, session_prompts, jobs, path_activations, command_activations, workspaces',
    'Hook does NOT call: resolveProtocol(), recordRun(), recordTrace()',
  ],
  conclusion: `Learning data is missing NOT because of a bug, but because of a design-level disconnection.
Pipeline itself doesn't record to DB, and Claude Code hooks don't trigger the pipeline.
To record, someone must explicitly run: lyo pipeline run + lyo run-start + lyo pipeline learn.
Except for dogfood, no such execution has occurred.`,
} as const;

// ============================================================================
// 9. RECOMMENDATIONS (encoded as actionable items)
// ============================================================================

export type RecommendationPriority = 'urgent' | 'medium_term' | 'long_term';
export type RecommendationStatus = 'not_started' | 'in_progress' | 'done';

export interface Recommendation {
  /** Recommendation identifier */
  id: string;
  /** Priority */
  priority: RecommendationPriority;
  /** Title */
  title: string;
  /** Description */
  description: string;
  /** Options if multiple approaches exist */
  options?: string[];
  /** Recommended approach */
  recommended?: string;
  /** Status */
  status: RecommendationStatus;
  /** Related gaps */
  relatedGaps?: string[];
}

export const RECOMMENDATIONS: Recommendation[] = [
  // URGENT
  {
    id: 'U1',
    priority: 'urgent',
    title: 'Make pipeline execution default',
    description: `Current lyo pipeline run records NOTHING to DB.
To collect learning data, must intentionally run:
  lyo run-start + lyo pipeline run + lyo pipeline learn
This sequence is error-prone and was skipped in 2 work repos.`,
    options: [
      'Option A: runPipeline() auto-calls recordRun() at start (RECOMMENDED)',
      'Option B: lyo pipeline run calls recordRun() as separate process',
      'Option C: Claude Code hook determines at session end if lyo pipeline run needed',
    ],
    recommended: 'Option A — simplest, reduces omission probability to zero',
    status: 'not_started',
    relatedGaps: ['GAP-007', 'GAP-008'],
  },
  {
    id: 'U2',
    priority: 'urgent',
    title: 'Decide whether to connect hook_events to learning pipeline',
    description: `crystalbrooks has 1977 hook_events, data-lake-rep-744 has 1575.
These prove "Claude Code session ran" but not what was done.

Question: If some sessions were actually spec-driven code/test generation,
can hook_events seed retroactive plan.json/spec.json reconstruction?`,
    options: [
      'Investigate actual work done via git log, file change history',
      'If spec-driven work found, reconstruct and run pipeline',
      'If not, hook_events remain isolated observations',
    ],
    status: 'not_started',
    relatedGaps: ['GAP-007'],
  },
  {
    id: 'U3',
    priority: 'urgent',
    title: 'Minimum execution plan for volume',
    description: `Goal: At least 2 repos × 3 full pipeline executions each (plan → run → learn).

Prerequisites:
1. plan.json + spec.json (lyo pipeline init --spec ...)
2. Test runner environment (node:test, CommonJS)
3. lyo pipeline run --plan plan.json → lyo pipeline learn --run <runDir> --library <dir>

Priority: Pick one repo with ongoing work. Start with simplest task that needs plan/spec.`,
    status: 'not_started',
    relatedGaps: ['GAP-004', 'GAP-007'],
  },

  // MEDIUM TERM
  {
    id: 'M1',
    priority: 'medium_term',
    title: 'Schema extension — add lesson_decisions table',
    description: `Add to src/schema.ts initLedger():

CREATE TABLE lesson_decisions (
  decision_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES runs(run_id),
  decision_time TEXT NOT NULL,
  candidate_set JSON NOT NULL,           -- [{lesson_path, sha256, alpha, beta}, ...]
  selected_lesson_path TEXT,             -- NULL = no-lesson arm
  selected_lesson_sha256 TEXT,
  selected_score REAL,                   -- Thompson draw θ
  selection_propensity REAL,             -- P(selected | candidate_set, posteriors) ← KEY
  task_shape TEXT NOT NULL,
  failure_class TEXT,
  cycle_index INTEGER,
  retry_count INTEGER,
  bandit_posterior_snapshot_id TEXT,
  seed TEXT,
  temperature REAL,
  model_id TEXT,
  tool_trace_hash TEXT,
  created_at TEXT NOT NULL
);

Insert around selectLessons() call in run-pipeline.ts.`,
    status: 'not_started',
    relatedGaps: ['GAP-002', 'GAP-003'],
  },
  {
    id: 'M2',
    priority: 'medium_term',
    title: 'Null-arm recording',
    description: `Record executions where no lesson was selected (selected_lesson_path = NULL).
Currently selectLessons() always selects up to 3, so null-arm only occurs when
library has no lessons. Becomes meaningful when intentional control cycles introduced.`,
    status: 'not_started',
    relatedGaps: ['GAP-006'],
  },
  {
    id: 'M3',
    priority: 'medium_term',
    title: 'Credit propagation fix',
    description: `Current (trace-consumer.ts:468-501):
  failure_class recurred → harmful
  expected → helpful
  else → nothing

Target (§3.2):
  w_i = h(ℓ_i | s_i, u') / ρ_i - 1

Immediate implementable: aggregate pass rate per lesson × failure_class,
compute lift vs overall pass rate, divide by propensity for ratio-lift estimate.`,
    status: 'not_started',
    relatedGaps: ['GAP-002'],
  },

  // LONG TERM
  {
    id: 'L1',
    priority: 'long_term',
    title: 'Secure 2+ failure classes',
    description: `Currently: output_generation only.
Goal: code-bug, test-hallucination, spec-gap — at least 2 more.

Method: Design tasks to elicit specific failures:
- Complex spec → code bugs
- Edge cases → test hallucinations
- Deliberately ambiguous spec → spec-gaps`,
    status: 'not_started',
    relatedGaps: ['GAP-004'],
  },
  {
    id: 'L2',
    priority: 'long_term',
    title: 'Secure 2+ models',
    description: `Currently: Claude Haiku only.
Blog draft used Solar Open2, GLM 5.2.
LYO pipeline should run with at least 2 model families.`,
    status: 'not_started',
    relatedGaps: ['GAP-004'],
  },
  {
    id: 'L3',
    priority: 'long_term',
    title: 'Track Ashby coverage metric',
    description: `§9: Coverage = observed failure classes / classes with active lessons.
Goal: 3/3 or better.
Current: 1/1 (meaningless — only one class to observe).`,
    status: 'not_started',
    relatedGaps: ['GAP-004'],
  },
];

/** What NOT to do (from recommendations) */
export const DO_NOT_DO = [
  'Shapley/leave-one-out coalition credit (COCOA deliberately avoids, §4)',
  'Full WCS rung-3 SCM replay — no environment model, model mis-specification bias risk (§4)',
  'Cycle-distance credit decay — COCOA Eq.1 critique (§4)',
  'Prose lessons as vehicle of first resort — blog draft\'s core lesson. Skeleton-patch / spec-constraint vehicles first.',
] as const;

// ============================================================================
// 10. QUICK-REFERENCE CONSTANTS
// ============================================================================

/** Repos with data */
export const REPOS_WITH_DATA = REPO_TELEMETRY_STATUS.filter((r) => r.pipelineExecuted);

/** Repos without data */
export const REPOS_WITHOUT_DATA = REPO_TELEMETRY_STATUS.filter((r) => !r.pipelineExecuted);

/** Total lessons in library (should be 1) */
export const TOTAL_LESSONS = 1;

/** Total runs that produced lessons */
export const TOTALRuns_THAT_PRODUCED_LESSON = RUNS_THAT_PRODUCED_LESSON.length;

/** Total deltas in audit log */
export const TOTAL_DELTAS = DELTA_LOG.length;

/** Number of schema gaps identified */
export const SCHEMA_GAP_COUNT = SCHEMA_GAPS_53.length;

/** Number of known gaps */
export const KNOWN_GAP_COUNT = KNOWN_GAPS.length;

/** Number of recommendations */
export const RECOMMENDATION_COUNT = RECOMMENDATIONS.length;

/** Urgent recommendations count */
export const URGENT_RECOMMENDATIONS_COUNT = RECOMMENDATIONS.filter((r) => r.priority === 'urgent').length;

/** Medium-term recommendations count */
export const MEDIUM_TERM_RECOMMENDATIONS_COUNT = RECOMMENDATIONS.filter((r) => r.priority === 'medium_term').length;

/** Long-term recommendations count */
export const LONG_TERM_RECOMMENDATIONS_COUNT = RECOMMENDATIONS.filter((r) => r.priority === 'long_term').length;
